using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum SceneIndex
{
    LOADING_SCENE = 0,
    MAIN_MENU = 1,
    FISHING_GAME_SCENE = 2,
    FISHING_GAME_SCENE_KIRI = 3,
    FISHING_GAME_SCENE_OCTOPUS = 4,
    FISHING_GAME_SCENE_BUFFALO = 5,
    FISHING_GAME_SCENE_LUKUI = 6,
    FISHING_GAME_SCENE_CHASINGWIND = 7,
    FISHING_GAME_SCENE_COINTREE = 8,
    FISHING_GAME_SCENE_FISHER = 9,
    FISHING_GAME_SCENE_DragonBall=10
}
